/**
 * Parameter definitions: metadata for all calculator inputs.
 * Shared across UI variants to avoid duplicating labels, ranges, and info text.
 */

export const PARAM_SECTIONS = [
  {
    id: 'stars',
    title: 'Stars, Planets and Moons',
    subtitle: 'Stellar and planetary parameters',
    resultKey: 'planetsInGalaxy',
    resultTemplate: (v) => `Your Milky Way has <strong>${v}</strong> planets in third-generation star systems.`,
    params: ['numberOfStars', 'ratioWithPlanets', 'planetsPerStar', 'ratioThirdGen'],
  },
  {
    id: 'life',
    title: 'Life-Supporting Conditions',
    subtitle: 'Factors required for life to emerge',
    resultKey: 'planetsCapableOfLife',
    resultTemplate: (v) => `Your Milky Way has <strong>${v}</strong> planets where life can emerge.`,
    params: [
      'ratioHabitableZone', 'ratioWithWater', 'ratioGuardianPlanet',
      'ratioIronCore', 'ratioSufficientMass', 'ratioChemicalPrerequisites', 'ratioLifeBegins',
    ],
  },
  {
    id: 'time',
    title: 'Time, Intelligent Life and Civilizations',
    subtitle: 'Temporal and sociological factors',
    params: [
      'ageThirdGen', 'timeForLifeToAppear', 'timeToIntelligentLife', 'timeToCivilization',
      'timeToDetectable', 'ratioCommunication', 'civilizationSurvival', 'civilizationsPerPlanet',
    ],
  },
];

/** Parameters shown in "Simple" mode (the 5 highest-impact sliders) */
export const SIMPLE_MODE_PARAMS = [
  'numberOfStars',
  'ratioLifeBegins',
  'civilizationSurvival',
  'civilizationsPerPlanet',
  'ratioCommunication',
];

export const PARAMS = {
  numberOfStars: {
    label: 'How many stars are in the Milky Way?',
    shortLabel: 'Stars in galaxy',
    min: 1, max: 1000, step: 1,
    unit: 'billion',
    hint: 'Most estimates: 100\u2013400 billion',
    info: 'The <a href="https://en.wikipedia.org/wiki/Milky_Way" target="_blank" rel="noopener">Milky Way</a> is a barred spiral galaxy with an estimated diameter of 100,000 light-years. Estimates of its total star count range from 100 to 400 billion.',
  },
  ratioWithPlanets: {
    label: 'What percentage of stars have planets?',
    shortLabel: 'Stars with planets',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Kepler data suggests 80\u2013100%',
    info: 'Data from <a href="https://en.wikipedia.org/wiki/Kepler_space_telescope" target="_blank" rel="noopener">Kepler</a> and TESS confirms that <strong>planets are the rule rather than the exception</strong>. At least one planet per star on average.',
  },
  planetsPerStar: {
    label: 'How many planets per star (including planet-like moons)?',
    shortLabel: 'Planets per star',
    min: 1, max: 20, step: 1,
    unit: 'pcs',
    hint: 'Our Solar System has 8 planets + large moons',
    info: 'Our Solar System has 8 planets, plus moons like Europa, Enceladus, and Titan that are potentially habitable. Kepler data suggests ~1.6 planets per Sun-like star.',
  },
  ratioThirdGen: {
    label: 'What percentage of stars are third-generation (metal-rich)?',
    shortLabel: '3rd-gen stars',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Required for rocky planets and life chemistry',
    info: 'Third-generation (Population I) stars contain heavy elements from earlier supernovae, essential for rocky planets and life chemistry. They dominate the Milky Way\u2019s thin disk (60\u201380% of stellar mass).',
  },
  ratioHabitableZone: {
    label: 'What fraction of planets are in the habitable zone?',
    shortLabel: 'Habitable zone',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'The "Goldilocks zone" \u2014 not too hot, not too cold',
    info: 'The habitable zone is where liquid water could exist on a planet\u2019s surface. For Sun-like stars, roughly 0.95 to 1.67 AU. Kepler suggests 0.37\u20130.88 rocky planets per Sun-like star in this zone.',
  },
  ratioWithWater: {
    label: 'What fraction of habitable planets have enough water?',
    shortLabel: 'Has water',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Water is abundant in the universe but "just right" amounts matter',
    info: 'Water is essential as a solvent for complex chemistry. It\'s abundant in the universe but too much creates ocean worlds lacking the land-ocean balance needed for chemical cycles.',
  },
  ratioGuardianPlanet: {
    label: 'What fraction of systems have a protective gas giant?',
    shortLabel: 'Guardian planet',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Like Jupiter deflecting asteroids (debated)',
    info: 'The Jupiter shield hypothesis is debated \u2014 gas giants may be "just as likely to send comets at Earth as deflect them." Gas giants are found around ~10\u201320% of Sun-like stars.',
  },
  ratioIronCore: {
    label: 'What fraction of planets have a magnetic field (iron core)?',
    shortLabel: 'Iron core',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Protects atmosphere from solar wind',
    info: 'A metallic core generates a magnetosphere that shields from solar wind and cosmic radiation. All 4 terrestrial planets in our Solar System have iron cores, but maintaining an active dynamo requires a liquid core.',
  },
  ratioSufficientMass: {
    label: 'What fraction of planets have enough mass to hold an atmosphere?',
    shortLabel: 'Sufficient mass',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Mars lost its atmosphere; Earth kept hers',
    info: 'A planet needs sufficient gravity to prevent atmospheric escape. Earth\u2019s mass is sufficient; Mars (~10% of Earth) has lost most of its atmosphere.',
  },
  ratioChemicalPrerequisites: {
    label: 'What fraction of habitable planets have the right chemistry?',
    shortLabel: 'Right chemistry',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'The "primordial soup" \u2014 organic molecules, energy sources',
    info: 'The primordial soup hypothesis: life arose from organic molecules energized by lightning, UV, or hydrothermal vents. A 2024 study argues only 0.003\u20130.2% may meet geological requirements (plate tectonics).',
  },
  ratioLifeBegins: {
    label: 'Even with all prerequisites met, what is the chance life actually begins?',
    shortLabel: 'Life begins',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'The transition from chemistry to biology',
    info: 'Abiogenesis remains one of the deepest unsolved problems. Life appeared on Earth within ~500 million years of habitable conditions, suggesting it may not be exceedingly rare.',
  },
  ageThirdGen: {
    label: 'Maximum age of third-generation star systems?',
    shortLabel: 'Age of 3rd-gen stars',
    min: 0.5, max: 13, step: 0.1,
    unit: 'bn yr',
    hint: 'The Milky Way is ~13.8 billion years old',
    info: 'The oldest Population I stars are up to 10 billion years old. Our Sun is about 4.6 billion years old.',
  },
  timeForLifeToAppear: {
    label: 'How long for life to appear after a planet forms?',
    shortLabel: 'Time for life',
    min: 0.1, max: 13, step: 0.1,
    unit: 'bn yr',
    hint: 'On Earth: ~0.5\u20131 billion years',
    info: 'On Earth, earliest life dates to 3.5\u20134.1 billion years ago, roughly 500 million to 1 billion years after the planet formed.',
  },
  timeToIntelligentLife: {
    label: 'How long from primitive life to intelligent life?',
    shortLabel: 'Time to intelligence',
    min: 0.1, max: 13, step: 0.1,
    unit: 'bn yr',
    hint: 'On Earth: ~3.5 billion years',
    info: 'On Earth, from first cells (~3.8 bya) to intelligent primates took roughly 3.5 billion years. The prokaryote-to-eukaryote transition alone took over 1 billion years.',
  },
  timeToCivilization: {
    label: 'How long from intelligent life to civilization?',
    shortLabel: 'Time to civilization',
    min: 0.01, max: 5, step: 0.01,
    unit: 'bn yr',
    hint: 'On Earth: ~0.0003 billion years (300,000 yr)',
    info: 'Homo sapiens appeared ~300,000 years ago; civilization (agriculture, writing) emerged ~10,000 years ago. Radio technology was invented ~100 years ago.',
  },
  timeToDetectable: {
    label: 'How long until a civilization produces detectable signals?',
    shortLabel: 'Time to signals',
    min: 100, max: 1_000_000, step: 1,
    unit: 'years',
    logScale: true,
    hint: 'Humans had radio for ~100 years out of 10,000 years of civilization',
    info: 'Earth was "dark" for 99% of its civilized history. This determines what fraction of a civilization\u2019s lifetime it spends broadcasting detectable technosignatures.',
  },
  ratioCommunication: {
    label: 'What fraction of civilizations develop detectable technology?',
    shortLabel: 'Detectable tech',
    min: 1, max: 100, step: 1,
    unit: '%',
    hint: 'Radio, laser, megastructures, pollution...',
    info: 'Even civilizations that don\u2019t intentionally broadcast will likely leak detectable emissions. However, they may transition to low-leakage technologies or deliberately stay silent (the "dark forest" hypothesis).',
  },
  civilizationSurvival: {
    label: 'How long do civilizations survive on average?',
    shortLabel: 'Survival time',
    min: 1, max: 10_000_000_000, step: 1,
    unit: 'years',
    logScale: true,
    adaptiveStep: true,
    scaleUnit: true,
    hint: 'From hundreds of years to billions \u2014 the biggest unknown',
    info: 'Estimates range from a few hundred years (self-destruction) to billions of years (long-term stability). This is one of the most uncertain parameters.',
  },
  civilizationsPerPlanet: {
    label: 'How many times can civilizations arise on the same planet?',
    shortLabel: 'Civs per planet',
    min: 1, max: 100, step: 1,
    unit: '',
    hint: 'Multiple civilizations across billions of years?',
    info: 'If civilizations are short-lived and a planet remains habitable for billions of years, multiple civilizations could arise in sequence. Mass extinctions reset the clock.',
  },
};
